// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc1
// source: math.proto

package math

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numa          int32                  `protobuf:"varint,1,opt,name=Numa,proto3" json:"Numa,omitempty"`
	Numb          int32                  `protobuf:"varint,2,opt,name=Numb,proto3" json:"Numb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_math_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_math_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_math_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2) GetNuma() int32 {
	if x != nil {
		return x.Numa
	}
	return 0
}

func (x *Vector2) GetNumb() int32 {
	if x != nil {
		return x.Numb
	}
	return 0
}

type Num struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Num) Reset() {
	*x = Num{}
	mi := &file_math_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Num) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Num) ProtoMessage() {}

func (x *Num) ProtoReflect() protoreflect.Message {
	mi := &file_math_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Num.ProtoReflect.Descriptor instead.
func (*Num) Descriptor() ([]byte, []int) {
	return file_math_proto_rawDescGZIP(), []int{1}
}

func (x *Num) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_math_proto protoreflect.FileDescriptor

const file_math_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"math.proto\"1\n" +
	"\aVector2\x12\x12\n" +
	"\x04Numa\x18\x01 \x01(\x05R\x04Numa\x12\x12\n" +
	"\x04Numb\x18\x02 \x01(\x05R\x04Numb\"\x17\n" +
	"\x03Num\x12\x10\n" +
	"\x03Num\x18\x01 \x01(\x05R\x03Num2<\n" +
	"\bMathUtil\x12\x17\n" +
	"\x03Add\x12\b.Vector2\x1a\x04.Num\"\x00\x12\x17\n" +
	"\x03Sub\x12\b.Vector2\x1a\x04.Num\"\x00B\bZ\x06.;mathb\x06proto3"

var (
	file_math_proto_rawDescOnce sync.Once
	file_math_proto_rawDescData []byte
)

func file_math_proto_rawDescGZIP() []byte {
	file_math_proto_rawDescOnce.Do(func() {
		file_math_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_math_proto_rawDesc), len(file_math_proto_rawDesc)))
	})
	return file_math_proto_rawDescData
}

var file_math_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_math_proto_goTypes = []any{
	(*Vector2)(nil), // 0: Vector2
	(*Num)(nil),     // 1: Num
}
var file_math_proto_depIdxs = []int32{
	0, // 0: MathUtil.Add:input_type -> Vector2
	0, // 1: MathUtil.Sub:input_type -> Vector2
	1, // 2: MathUtil.Add:output_type -> Num
	1, // 3: MathUtil.Sub:output_type -> Num
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_math_proto_init() }
func file_math_proto_init() {
	if File_math_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_math_proto_rawDesc), len(file_math_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_math_proto_goTypes,
		DependencyIndexes: file_math_proto_depIdxs,
		MessageInfos:      file_math_proto_msgTypes,
	}.Build()
	File_math_proto = out.File
	file_math_proto_goTypes = nil
	file_math_proto_depIdxs = nil
}
