// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.0--rc1
// source: math.proto

package math

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MathUtil_Add_FullMethodName = "/MathUtil/Add"
	MathUtil_Sub_FullMethodName = "/MathUtil/Sub"
)

// MathUtilClient is the client API for MathUtil service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MathUtilClient interface {
	Add(ctx context.Context, in *Vector2, opts ...grpc.CallOption) (*Num, error)
	Sub(ctx context.Context, in *Vector2, opts ...grpc.CallOption) (*Num, error)
}

type mathUtilClient struct {
	cc grpc.ClientConnInterface
}

func NewMathUtilClient(cc grpc.ClientConnInterface) MathUtilClient {
	return &mathUtilClient{cc}
}

func (c *mathUtilClient) Add(ctx context.Context, in *Vector2, opts ...grpc.CallOption) (*Num, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Num)
	err := c.cc.Invoke(ctx, MathUtil_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathUtilClient) Sub(ctx context.Context, in *Vector2, opts ...grpc.CallOption) (*Num, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Num)
	err := c.cc.Invoke(ctx, MathUtil_Sub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathUtilServer is the server API for MathUtil service.
// All implementations must embed UnimplementedMathUtilServer
// for forward compatibility.
type MathUtilServer interface {
	Add(context.Context, *Vector2) (*Num, error)
	Sub(context.Context, *Vector2) (*Num, error)
	mustEmbedUnimplementedMathUtilServer()
}

// UnimplementedMathUtilServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMathUtilServer struct{}

func (UnimplementedMathUtilServer) Add(context.Context, *Vector2) (*Num, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedMathUtilServer) Sub(context.Context, *Vector2) (*Num, error) {
	return nil, status.Error(codes.Unimplemented, "method Sub not implemented")
}
func (UnimplementedMathUtilServer) mustEmbedUnimplementedMathUtilServer() {}
func (UnimplementedMathUtilServer) testEmbeddedByValue()                  {}

// UnsafeMathUtilServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MathUtilServer will
// result in compilation errors.
type UnsafeMathUtilServer interface {
	mustEmbedUnimplementedMathUtilServer()
}

func RegisterMathUtilServer(s grpc.ServiceRegistrar, srv MathUtilServer) {
	// If the following call panics, it indicates UnimplementedMathUtilServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MathUtil_ServiceDesc, srv)
}

func _MathUtil_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vector2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathUtilServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathUtil_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathUtilServer).Add(ctx, req.(*Vector2))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathUtil_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vector2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathUtilServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathUtil_Sub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathUtilServer).Sub(ctx, req.(*Vector2))
	}
	return interceptor(ctx, in, info, handler)
}

// MathUtil_ServiceDesc is the grpc.ServiceDesc for MathUtil service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MathUtil_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MathUtil",
	HandlerType: (*MathUtilServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _MathUtil_Add_Handler,
		},
		{
			MethodName: "Sub",
			Handler:    _MathUtil_Sub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "math.proto",
}
